SELECT
    LGM_STOCKBASELISTV.BOOKSTATENR,
    LGM_STOCKBASELISTV.IDTYPE,
    LGM_STOCKBASELISTV.ID,
    LGM_STOCKBASELISTV.STOCKTYPEID,
    ABS(LGM_STOCKBASELISTV.COUNTNEW)     AS COUNTNEW,
    ABS(LGM_STOCKBASELISTV.COUNTUSED)    AS COUNTUSED,
    ABS(LGM_STOCKBASELISTV.COUNTREPAIR)  AS COUNTREPAIR,
    LGM_STOCKBASELISTV.STOCKPLACEID,
    ISNULL(TMS_COSTUNITSTOCKPLACE.NAME00, TMS_COSTUNITSTOCKPLACE.NAME) AS COSTUNITSTOCKPLACENAME,
    TMS_COSTUNITSTOCKPLACE.HALL,
    TMS_COSTUNITSTOCKPLACE.SHELF,
    TMS_COSTUNITSTOCKPLACE.DRAWER,
    TMS_COSTUNITSTOCKPLACE.GRID,
    TMS_COSTUNITSTOCKPLACE.WIDTH,
    TMS_COSTUNITSTOCKPLACE.DEPTH,
    TMS_COSTUNITSTOCKPLACE.HEIGHT,
    TMS_COSTUNITSTOCKPLACE.DEVICETYPE,
    TMS_COSTUNITSTOCKPLACE.DEVICEID,
    LGM_STOCKBASELISTV.COSTUNIT,
    LGM_STOCKBASELISTV.WORKPLACE,
    LGM_STOCKBASELISTV.ACCOUNTID,
    CONVERT(VARCHAR(23), LGM_STOCKBASELISTV.CANCELNR) AS CANCELNRs,
    LGM_STOCKBASELISTV.INVID,
    LGM_HISTORYBASE.BOOKTIMESTAMP,
    LGM_STOCKBASELISTV.[TIMESTAMP],
    CONVERT(char(10),DATEADD(SECOND,LGM_HISTORYBASE.BOOKTIMESTAMP,CAST('1970-01-01T00:00:00' AS datetime2)),104) AS BOOKDATE,
    CONVERT(char(8),DATEADD(SECOND,LGM_HISTORYBASE.BOOKTIMESTAMP,CAST('1970-01-01T00:00:00' AS datetime2)),108) AS BOOKTIME,    
    DBO.Tms_Idv_F_Getname(LGM_STOCKBASELISTV.IDTYPE, LGM_STOCKBASELISTV.ID, N'00')  AS NAME,
    DBO.Tms_Idv_F_Getname2(LGM_STOCKBASELISTV.IDTYPE, LGM_STOCKBASELISTV.ID, N'00') AS NAME2,
    LGM_HISTORYBASE.COSTUNITTO,
    LGM_HISTORYBASE.WORKPLACETO,
    LGM_HISTORYBASE.USERID,
    LGM_HISTORYBASE.LISTID,
    LGM_HISTORYBASE.AREA,
    LGM_HISTORYBASE.BOOKTYPE,
    TMS_DEVICE.MOD,
    COALESCE(cml_to.MACHINEID, cml_from.MACHINEID) AS MACHINEID,
    COALESCE(m_to.NAME, m_from.NAME)                AS MACHINENAME
FROM LGM_STOCKBASELISTV

INNER JOIN LGM_HISTORYBASE
    ON  LGM_HISTORYBASE.ID       = LGM_STOCKBASELISTV.ID
   AND LGM_HISTORYBASE.IDTYPE   = LGM_STOCKBASELISTV.IDTYPE
   AND LGM_HISTORYBASE.CANCELNR = LGM_STOCKBASELISTV.CANCELNR

INNER JOIN TMS_IDV
    ON  TMS_IDV.ID    = LGM_STOCKBASELISTV.ID
   AND TMS_IDV.IDTYPE = LGM_STOCKBASELISTV.IDTYPE

LEFT OUTER JOIN TMS_COSTUNITSTOCKPLACE
    ON  LGM_STOCKBASELISTV.STOCKPLACEID = TMS_COSTUNITSTOCKPLACE.STOCKPLACEID
   AND LGM_STOCKBASELISTV.COSTUNIT     = TMS_COSTUNITSTOCKPLACE.COSTUNIT
   AND LGM_STOCKBASELISTV.WORKPLACE    = TMS_COSTUNITSTOCKPLACE.WORKPLACE

LEFT OUTER JOIN TMS_DEVICE
    ON TMS_COSTUNITSTOCKPLACE.DEVICEID = TMS_DEVICE.DEVICEID

LEFT JOIN TMS_COSTUNITMACHINELIST cml_to
    ON  cml_to.COSTUNIT   = LGM_HISTORYBASE.COSTUNITTO
   AND cml_to.WORKPLACE   = LGM_HISTORYBASE.WORKPLACETO

LEFT JOIN TDM_MACHINE m_to
    ON m_to.MACHINEID = cml_to.MACHINEID

LEFT JOIN TMS_COSTUNITMACHINELIST cml_from
    ON  cml_from.COSTUNIT   = LGM_HISTORYBASE.COSTUNITFROM
   AND cml_from.WORKPLACE   = LGM_HISTORYBASE.WORKPLACEFROM

LEFT JOIN TDM_MACHINE m_from
    ON m_from.MACHINEID = cml_from.MACHINEID

WHERE
    (LGM_STOCKBASELISTV.BOOKSTATENR = -1 OR LGM_STOCKBASELISTV.BOOKSTATENR = 1)
    AND LGM_STOCKBASELISTV.COSTUNIT   = N'1703169000'
    AND LGM_STOCKBASELISTV.WORKPLACE  = N'B12 ZENTRALLAGER'

ORDER BY
    TMS_COSTUNITSTOCKPLACE.HALL,
    TMS_COSTUNITSTOCKPLACE.SHELF,
    TMS_COSTUNITSTOCKPLACE.DRAWER,
    TMS_COSTUNITSTOCKPLACE.GRID,
    TMS_COSTUNITSTOCKPLACE.WIDTH,
    TMS_COSTUNITSTOCKPLACE.DEPTH,
    TMS_COSTUNITSTOCKPLACE.HEIGHT;