SELECT
  HB.BOOKTIMESTAMP,
  CONVERT(char(10),DATEADD(SECOND,HB.BOOKTIMESTAMP,CAST('1970-01-01T00:00:00' AS datetime2)),104) AS BOOKDATE,
  CONVERT(char(8),DATEADD(SECOND,HB.BOOKTIMESTAMP,CAST('1970-01-01T00:00:00' AS datetime2)),108) AS BOOKTIME,
    HB.ID,
  HB.BOOKTYPE as TYPE,
  HB.IDTYPE AS COMPORTOOL,
  HB.COSTUNITFROM,
  HB.WORKPLACEFROM,
  HB.COSTUNITTO,
  HB.WORKPLACETO,
  HB.COUNTNEW,
  HB.COUNTUSED,
  HB.COUNTREPAIR,
  HB.COSTCORRELATIONFLAG AS COSTCORRELATION,
  HB.STATE,
  HB.FACTOR,
  HB.COSTUNITCOSTS,
  HB.WORKPLACECOSTS,
  HB.ACCOUNTID,
  HB.BOOKTEXT,
  HB.USERID,
  HB.CANCELNR,
  FLOOR(HB.CANCELNR) AS CANCELNR_BASE,
  DBO.Tms_Idv_F_Getname(HB.IDTYPE, HB.ID, N'01') AS NAME,
  DBO.Tms_Idv_F_Getname2(HB.IDTYPE, HB.ID, N'01') AS NAME2,
  LGM_Package.Lgm_HistoryBaseList_F_GetInvid(HB.CANCELNR) AS INVID,
  LGM_Package.Lgm_HistoryBaseList_F_GetStPId(HB.CANCELNR) AS STOCKPLACEID,
  HB.LISTID,
  HB.TRANSACTIONNR,
  HB.TRANSACTIONLISTPOS,
  HB.COMMISSIONID,
  HB.PLANNEDFINISHTIMESTAMP,
  HB.TRANSACTIONREASONID,
  HB.AREA,
  SP.HALL,
  SP.SHELF,
  SP.DRAWER,
  SP.WIDTH,
  SP.HEIGHT,
  SP.[DEPTH],
  SP.DEVICEID,
  SP.DEVICETYPE,
  COALESCE(CML_TO.MACHINEID, CML_FROM.MACHINEID) AS MACHINEID,
  COALESCE(M_TO.NAME, M_FROM.NAME) AS MACHINENAME,
  CASE HB.IDTYPE
    WHEN 2 THEN CSB.BOOKSTATENR
    WHEN 1 THEN TSB.BOOKSTATENR
  END AS BOOKSTATENR
FROM TMS.LGM_HISTORYBASE HB
INNER JOIN (
  SELECT DISTINCT FLOOR(CANCELNR) AS CANCELNR_BASE
  FROM TMS.LGM_STOCKBASELISTV
  WHERE COSTUNIT = :costunit
    AND WORKPLACE = :workplace
    AND (BOOKSTATENR = -1 OR BOOKSTATENR = 1)
) UB ON FLOOR(HB.CANCELNR) = UB.CANCELNR_BASE
LEFT JOIN TMS.LGM_COSTUNITSTOCKPLACE SP
  ON SP.COSTUNIT = HB.COSTUNITFROM
  AND SP.WORKPLACE = HB.WORKPLACEFROM
  AND SP.STOCKPLACEID = LGM_Package.Lgm_HistoryBaseList_F_GetStPId(HB.CANCELNR)
LEFT JOIN TMS.TMS_COSTUNITMACHINELIST CML_TO
  ON CML_TO.COSTUNIT = HB.COSTUNITTO
  AND CML_TO.WORKPLACE = HB.WORKPLACETO
LEFT JOIN TMS.TDM_MACHINE M_TO
  ON M_TO.MACHINEID = CML_TO.MACHINEID
LEFT JOIN TMS.TMS_COSTUNITMACHINELIST CML_FROM
  ON CML_FROM.COSTUNIT = HB.COSTUNITFROM
  AND CML_FROM.WORKPLACE = HB.WORKPLACEFROM
LEFT JOIN TMS.TDM_MACHINE M_FROM
  ON M_FROM.MACHINEID = CML_FROM.MACHINEID
-- IDTYPE=2: Component stock
LEFT JOIN TMS.LGM_COMPSTOCKBASELIST CSB
  ON HB.IDTYPE = 2
  AND CSB.CANCELNR = HB.CANCELNR
  AND CSB.COSTUNIT = :costunit
  AND CSB.WORKPLACE = :workplace
  AND CSB.COMPID = HB.ID
  AND ISNULL(CSB.COMPINVID, '') = ISNULL(LGM_Package.Lgm_HistoryBaseList_F_GetInvid(HB.CANCELNR), '')
  AND ISNULL(CSB.STOCKPLACEID, '') = ISNULL(LGM_Package.Lgm_HistoryBaseList_F_GetStPId(HB.CANCELNR), '')
-- IDTYPE=1: Tool stock
LEFT JOIN TMS.LGM_TOOLSTOCKBASELIST TSB
  ON HB.IDTYPE = 1
  AND TSB.CANCELNR = HB.CANCELNR
  AND TSB.COSTUNIT = :costunit
  AND TSB.WORKPLACE = :workplace
  AND TSB.TOOLID = HB.ID
  AND ISNULL(TSB.TOOLINVID, '') = ISNULL(LGM_Package.Lgm_HistoryBaseList_F_GetInvid(HB.CANCELNR), '')
  AND ISNULL(TSB.STOCKPLACEID, '') = ISNULL(LGM_Package.Lgm_HistoryBaseList_F_GetStPId(HB.CANCELNR), '')
WHERE HB.BOOKTYPE <> -6
  AND HB.BOOKTYPE <> -7
ORDER BY HB.BOOKTIMESTAMP DESC, HB.CANCELNR DESC

