-- Extracted unique SQL queries from sql_confir_log.sql
-- Total found: 15, Unique: 14

-- Query 1
DELETE FROM TMPXXYYZZ_TMS_ZZYYXXTMP_LGM_COMPSTOCKBASELIST
WHERE  COSTUNIT    = '@@@N@@@1703169000'
  AND  WORKPLACE   = '@@@N@@@B12 ZENTRALLAGER'
  AND  COMPID      = '@@@N@@@C0001258'
  AND  STOCKTYPEID IS NULL
  AND  COMPINVID   IS NULL
  AND  STOCKPLACEID = '@@@N@@@0103005040010201'
  AND  BOOKSTATENR = -1
  AND  CONVERT(VARCHAR(23), CANCELNR) LIKE '@@@N@@@79148454100.003000%'

-- Query 2
DELETE FROM TMPXXYYZZ_TMS_ZZYYXXTMP_LGM_COMPSTOCKBASELIST
WHERE  COSTUNIT    = '@@@N@@@1703169000'
  AND  WORKPLACE   = '@@@N@@@B12 ZENTRALLAGER'
  AND  COMPID      = '@@@N@@@C0001258'
  AND  STOCKTYPEID IS NULL
  AND  COMPINVID   IS NULL
  AND  STOCKPLACEID = '@@@N@@@0103005040010201'
  AND  CANCELNR    = 79148454100.003000
  AND  BOOKSTATENR = -1

-- Query 3
DELETE FROM TMPXXYYZZ_TMS_ZZYYXXTMP_LGM_TMPLISTBASE
WHERE  SUBSYSID LIKE '@@@N@@@1770730345%'

-- Query 4
DELETE FROM TMPXXYYZZ_TMS_ZZYYXXTMP_LGM_TMPLISTBASELIST
WHERE  SUBSYSID LIKE '@@@N@@@1770730345%'

-- Query 5
SELECT (COSTUNIT + ('@@@N@@@.' + WORKPLACE)) AS COSTUNITWORKPLACE,
       TYPE,
       EXTSYSTEM,
       EXTSYSTEMTYPE,
       STOCKPLACETYPE,
       LOCKED
FROM   TMS_COSTUNIT

-- Query 6
SELECT COSTUNIT,
       WORKPLACE
FROM   TMS_COSTUNIT A
WHERE  A.TYPE = 4
  AND  NOT EXISTS (
         SELECT B1.COMPID
         FROM   LGM_COMPSTOCKBASELIST B1
         WHERE  B1.COSTUNIT  = A.COSTUNIT
           AND  B1.WORKPLACE = A.WORKPLACE
       )
  AND  NOT EXISTS (
         SELECT B2.TOOLID
         FROM   LGM_TOOLSTOCKBASELIST B2
         WHERE  B2.COSTUNIT  = A.COSTUNIT
           AND  B2.WORKPLACE = A.WORKPLACE
       )

-- Query 7
SELECT COSTUNIT,
       WORKPLACE,
       COMPID AS ID,
       1 AS IDTYPE,
       STOCKTYPEID,
       COMPINVID AS INVID,
       STOCKPLACEID,
       BOOKSTATENR,
       CONVERT(VARCHAR(23), CANCELNR) AS CANCELNR,
       COUNTNEW,
       COUNTUSED,
       COUNTREPAIR,
       ACCOUNTID
FROM   TMPXXYYZZ_TMS_ZZYYXXTMP_LGM_COMPSTOCKBASELIST
WHERE  COSTUNIT    = '@@@N@@@1703169000'
  AND  WORKPLACE   = '@@@N@@@B12 ZENTRALLAGER'
  AND  COMPID      = '@@@N@@@C0001258'
  AND  STOCKTYPEID IS NULL
  AND  COMPINVID   IS NULL
  AND  STOCKPLACEID = '@@@N@@@0103005040010201'
  AND  BOOKSTATENR = -1
  AND  CONVERT(VARCHAR(23), CANCELNR) LIKE '@@@N@@@79148454100.003000%'

-- Query 8
SELECT COUNT(LGM_STOCKBASELISTV.ID),
       CASE
         WHEN COUNT(LGM_STOCKBASELISTV.ID) = 0 THEN NULL
         ELSE '@@@N@@@hook'
       END
FROM   LGM_STOCKBASELISTV
WHERE  LGM_STOCKBASELISTV.COSTUNIT  = '@@@N@@@1703169000'
  AND  LGM_STOCKBASELISTV.WORKPLACE = '@@@N@@@B12 ZENTRALLAGER'
  AND  LGM_STOCKBASELISTV.BOOKSTATENR IN (1, -1)

-- Query 9
SELECT CANCELNR
FROM   LGM_CANCEL
WHERE  FLOOR(CANCELNR) = FLOOR(79148454100.003000)
  AND  CANCELTIMESTAMP IS NOT NULL

-- Query 10
SELECT ID
FROM   TMPXXYYZZ_TMS_ZZYYXXTMP_LGM_STOCKBASELISTV
WHERE  CANCELNR    >= 79148454100.0
  AND  CANCELNR    <  79148454100.0 + 1
  AND  BOOKSTATENR IN (-1, -2, -5, -6)

-- Query 11
UPDATE TMPXXYYZZ_TMS_ZZYYXXTMP_LGM_COMPSTOCKBASELIST
SET    TIMESTAMP   = 1770745878,
       COUNTNEW    = COUNTNEW - -1,
       COUNTUSED   = COUNTUSED - 0,
       COUNTREPAIR = COUNTREPAIR - 0
WHERE  COMPID      = '@@@N@@@C0001258'
  AND  STOCKTYPEID IS NULL
  AND  COMPINVID   IS NULL
  AND  BOOKSTATENR = -4
  AND  CANCELNR    >= 79148454100.003000
  AND  CANCELNR    <  79148454100.0 + 1
  AND  EXISTS (
         SELECT COSTUNIT
         FROM   TMS_COSTUNIT
         WHERE  LGM_COMPSTOCKBASELIST.COSTUNIT  = TMS_COSTUNIT.COSTUNIT
           AND  LGM_COMPSTOCKBASELIST.WORKPLACE = TMS_COSTUNIT.WORKPLACE
           AND  TYPE = 1
       )

-- Query 12
UPDATE TMPXXYYZZ_TMS_ZZYYXXTMP_LGM_COMPSTOCKBASELIST
SET    TIMESTAMP   = 1770745878,
       COUNTNEW    = COUNTNEW - 0,
       COUNTUSED   = COUNTUSED - -1,
       COUNTREPAIR = COUNTREPAIR - 0
WHERE  COMPID      = '@@@N@@@C0001258'
  AND  STOCKTYPEID IS NULL
  AND  COMPINVID   IS NULL
  AND  BOOKSTATENR = -4
  AND  CANCELNR    >= 79148454100.003000
  AND  CANCELNR    <  79148454100.0 + 1
  AND  EXISTS (
         SELECT COSTUNIT
         FROM   TMS_COSTUNIT
         WHERE  LGM_COMPSTOCKBASELIST.COSTUNIT  = TMS_COSTUNIT.COSTUNIT
           AND  LGM_COMPSTOCKBASELIST.WORKPLACE = TMS_COSTUNIT.WORKPLACE
           AND  TYPE <> 1
       )

-- Query 13
UPDATE TMPXXYYZZ_TMS_ZZYYXXTMP_LGM_COMPSTOCKBASELIST
SET    TIMESTAMP   = 1770745878,
       COUNTNEW    = COUNTNEW + -1,
       COUNTUSED   = COUNTUSED + 0,
       COUNTREPAIR = COUNTREPAIR + 0,
       ACCOUNTID   = NULL
WHERE  COSTUNIT     = '@@@N@@@1703169000'
  AND  WORKPLACE    = '@@@N@@@B12 ZENTRALLAGER'
  AND  COMPID       = '@@@N@@@C0001258'
  AND  STOCKTYPEID  IS NULL
  AND  COMPINVID    IS NULL
  AND  STOCKPLACEID = '@@@N@@@0103005040010201'
  AND  (COUNTNEW + -1)    >= 0
  AND  (COUNTUSED + 0)    >= 0
  AND  (COUNTREPAIR + 0)  >= 0
  AND  CANCELNR     IS NULL
  AND  BOOKSTATENR  = 0

-- Query 14
UPDATE TMPXXYYZZ_TMS_ZZYYXXTMP_LGM_HISTORYBASELIST
SET    TIMESTAMP     = 1770745878,
       VALIDATESTATE = 2
WHERE  CANCELNR     = 79148454100.003000
  AND  STOCKPLACEID = '@@@N@@@0103005040010201'
  AND  COUNTNEW     = -1
  AND  COUNTUSED    = 0
  AND  COUNTREPAIR  = 0
